#' Run the Replacement Application
#'
#' @description This will start the Grid Replacment Application which is part of the Survey Solutions Spatial
#' Sampling toolbox. To use it, make sure you have access to the frame files generated by the Spatial Sampling
#' application.
#'
#' @param mapboxkey mapbox key required for your basemap.
#' @param bgmaptype the type of mapbox map, one of: "dark", "light", "outdoors",
#' "streets", "satellite", "satellite-streets".
#' @param pghost Postgres host address, default is localhost
#' @param pguser Postgres user.
#' @param pgpass Postgres password.
#' @param pgdbname Postgress database name.
#' @param filepath Name of the directory where the files for the background maps are stored during processing. If
#' this folder does not exists, it will be created in the current working directory.
#' @param susomapcrs Coordinate reference system for fieldwork maps. Must be compatible with Survey Solutions. If you are
#' not sure, leave it at the default 3857, web-mercator.
#' @param ... arguments to pass to golem_opts.
#' See `?golem::get_golem_options` for more details.
#' @inheritParams shiny::shinyApp
#'
#' @export
#' @importFrom shiny shinyApp
#' @importFrom golem with_golem_options
#'
run_app <- function(
  bgmaptype = "streets",
  mapboxkey = NULL,
  pghost = "localhost",
  pguser = "shiny",
  pgpass = NULL,
  pgdbname = "spatsampdata",
  filepath = "susomaps",
  susomapcrs = 3857,
  onStart = NULL,
  options = list(),
  enableBookmarking = NULL,
  uiPattern = "/",
  ...
) {
  with_golem_options(
    app = shinyApp(
      ui = app_ui,
      server = app_server,
      onStart = onStart,
      options = list(launch.browser=T),
      enableBookmarking = enableBookmarking,
      uiPattern = uiPattern
    ),
    golem_opts = list(KEY = mapboxkey,
                      bgmaptype = bgmaptype,
                      pghost = pghost,
                      pguser = pguser,
                      pgpass = pgpass,
                      pgdbname = pgdbname,
                      filepath = filepath,
                      susomapcrs = susomapcrs)
  )
}
